### ISSUE TITLE
how to run your own solution?

### ISSUE THREAD

**Issue by Kuznetsov-Ilia** [containerum/chkit#80]
I would like to run my own local solution with my .containerum.json / deploy.json / service.json.
Is there any way to do that? I'd like to try `chkit solution run .`, but solution seems to be broken at 3.0.2-beta. And pls, add choice to file format, yaml is much, mush more preferable...

**Comment by ninedraft** [comment]
Hello! Unfortunately, the function of launching custom solutions is currently under construction because of the massive architecture rearrangement. Most likely, this feature will come into operation before the end of next week. If you want, I can notify you about the readiness of user-defined solutions in this issue.

**Comment by Kuznetsov-Ilia** [comment]
Yep, pls notify me. I'll try to use current instruments for my petproject...
